name: Build and test

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Install NumPy
              run:  pip3 install numpy
            - name: Generate the training dataset
              run:  python3 Training_datasets_generator.py3
            - name: Move to the NeuralNetwork subdirectory
              run:  cd NeuralNetwork
            - name: Build the network
              run:  make -j3 options=OptionLists/Ubuntu_GNU_CI.cfg
            - name: Run
              run:  ./NeuralNetwork_exe
